# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bureau Zeven Sloten
description: Alles begint met een verhaal. Haarlems bureau voor <a href="#theater" class="alloy-anchor">theater</a>, <a href="#film" class="alloy-anchor">film</a> & <a href="#documentaires" class="alloy-anchor">documentaires</a>.
tagline: theater, film & documentaires

author: Sophie van Os
bio:
email: sophie@bureauzevensloten.nl
phone: 06 12 99 51 30
baseurl: "/bureauzevensloten" # the subpath of your site, e.g. /blog
url: "https://mvaneijgen.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sophiejpvanos
instagram_username: sophiejpvanos
facebook_username: sophiejpvanos
linkedin_username: sophiejpvanos
age: "25 juni 1991"
location: "Haarlem"

divider: "-"
separator: "-"

lang: nl

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  sections:
    output: false
  klanten:
    output: false
  projecten:
    output: false
  intern:
    output: false
  school:
    output: false
  work:
    output: false
    # permalink: /:name

excerpt_separator: ""
